
<!DOCTYPE html>
   <html lang="en">
      <head>
         <meta charset="utf-8" />
         <meta name="description" content="MSL Medical Context" />
         <meta name="keywords" content="Homepage" />
         <meta name="author" content="Brandon Lai"  />
         <title> Homepage</title>
         <link rel="stylesheet" type="text/css" href="styles/style.css">
         <link rel="stylesheet" href="https://unpkg.com/boxicons@latest/css/boxicons.min.css">
       </head>

<?php

echo"<footer>
         <section class='footer'>
         <div class='footer-content'>
            <img src='images/MSL_logo.png' alt='logo'>
            <p><em>Welcome the Malaysia Sign Language Society! <br>
            We are dedicated to your needs.</em></p>

            <p><a href='https://youtu.be/wXs5nk776Nw'>Link to youtube presentation video assignment 2</a></p>
   
   <br>
         <div class='footer-container'>
            <h4>Contact Us</h4>
            <ul>
               <li><a href='tel:+608256789'>(60) 82-567-89</a></li>
            </ul>
         </div>

        
          
           <div class='footer-icons'>
            <ul>
               <li><a href='https://www.facebook.com/sarawaksocietyforthedeaf'><img src='images/facebook.png' alt='Facebook'></a></li>
               <li><a href='https://www.instagram.com/sarawak_societyforthedeaf/'><img src='images/instagram.png' alt='Instagram'></a></li>
               <li><a href='https://www.youtube.com/@canineaddict1'><img src='images/youtube.png' alt='youtube'></a></li>
               <li><a href='mailto:ssdkuching1982@gmail.com'><img src='images/email.png' alt='email'></a></li>
            </ul>
         </div>
           
         
         <div id='mail' >
            <a href='mailto:102787664@students.swinburne.edu.my'><p>Email Me</p></a>
            </div>
         </div> 


         <div class='footer-content'>
            
            <div class='footer-container'>
                
                <h4>Services</h4>
                   <li><a href='services.php'>Services</a></li>
                <li><a href='service1.php'>BIM Class</a></li>
                <li><a href='service2.php'>Haircut and Trimming</a></li>
                <li><a href='service3.php'>Sewing And Alteration</a></li>
                <li><a href='service4.php'>Charity Car Wash</a></li>
             </div>
       
             <div class='footer-container'>
                <h4>Profiles</h4>
                <li><a href='aeron.php'>Aeron Liu</a></li>
                <li><a href='brandon.php'>Brandon Lai</a></li>
                <li><a href='rachel.php'>Rachel Chong</a></li>
                <li><a href='seow_zi_jie.php'>Seow Zi Jie</a></li>
                <li><a href='zaferah.php'>Zaferah</a></li>
             </div>
       
             <div class='footer-container'>
                <h4>Forms</h4>
                <li><a href='enquiryservice.php'>Enquiry for Services Form</a></li>
                <li><a href='Joinvolunteer.php'>Volunteer Form</a></li>
             </div>
       
             <div class='footer-container'>
                <h4>Others</h4>
                <li><a href='assign2index.php'>Home</a></li>
                <li><a href='activities.php'>Activites</a></li>
                <li><a href='enhancement1.php'>Enhancement</a></li>
                <li><a href='login.php'>Login</a></li>
                <li><a href='sign-up.php'>Sign up</a></li>
                <li><a href='FAQ.php'>FAQ page</a></li>
                <li><a href='acknowledgements.php'>Acknowledgements</a></li>
                </div>
       
             </div>
      
         </section>
   </footer>"

?>